[bot]
server: chardaan.cosmi.co.in
debug: false

[secrets]
secrets_path: /home/klipper/moonraker-telegram-bot-secrets/secrets.conf

[camera]
host: http://chardaan.cosmi.co.in/webcam/?action=stream
flip_vertically: false
flip_horizontally: false
video_duration: 15
fps: 30
picture_quality: high

[progress_notification]
percent: 5
time: 600

[timelapse]
cleanup: true
manual_mode: true
height: 0.2
target_fps: 30	
